config/routes.rb
Rails.application.routes.draw do


  root 'questions#index'

  resources :questions, except: :new do
    member do
      patch 'upvote', to: 'questions#upvote'
      patch 'downvote', to: 'questions#downvote'
    end
    resources :answers, only: [:create], param: :answer_id do
      member do
        patch 'upvote', to: 'answers#upvote'
        patch 'downvote', to: 'answers#downvote'
      end
    end
  end
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
  default_scope -> { order(votes: :desc)}
  validates :title, presence: true
  validates :content, presence: true

  def upvote
    self.votes += 1
    self.save
  end

  def downvote
    self.votes -= 1
    self.save
  end
end

app/models/github.rb
require 'quote'

module Github

  class Client
    include HTTParty
    base_uri "https://api.github.com"

    def get(access_token)
      headers = {"User-Agent" => "shinshinwu"}
      response = self.class.get("/zen", :query => { :access_token => access_token })
      if response.code == 403
        return Quote.find(rand(1..Quote.all.count)).quote
      else
        return response
      end
    end
  end

end

app/models/question.rb
class Question < ActiveRecord::Base
  has_many :answers, dependent: :destroy
  validates :title, presence: true
  validates :content, presence: true

  def upvote
    self.votes += 1
    self.save
  end

  def downvote
    self.votes -= 1
    self.save
  end
end

app/models/quote.rb
class Quote < ActiveRecord::Base

end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  respond_to :html, :js

  def create
    @question = Question.find(params[:question_id])
    @answer = Answer.new(answer_params)
    @question.answers << @answer
    respond_to do |format|
      if @answer.save
        flash[:success] = "Answer successfully posted!"
        format.js {}
        format.html { redirect_to question_path(params[:question_id]) }
      else
        redirect_to question_path(params[:question_id])
      end
    end
  end

  def upvote
    @answer = Answer.find(params[:answer_id])
    respond_to do |format|
      @answer.upvote
      format.js {}
      format.html { redirect_to question_path(params[:question_id]) }
    end
  end

  def downvote
    @answer = Answer.find(params[:answer_id])
    respond_to do |format|
      @answer.downvote
      format.js {}
      format.html { redirect_to question_path(params[:question_id]) }
    end
  end

  private
    def answer_params
      params.require(:answer).permit(:title, :content)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  respond_to :html, :js

  def index
    api = Github::Client.new
    @quote = api.get(ENV['TOKEN'])
    print = ENV['TEST']
    p print
    @question = Question.new
    @questions = Question.all
  end

  def show
    @question = Question.find(params[:id])
    @answers = @question.answers.paginate(page: params[:page])
    @answer = Answer.new
  end

  def create
    @question = Question.new(question_params)
    respond_to do |format|
      if @question.save
        flash[:success] = "Question successfully posted!"
        format.js {}
        format.html { redirect_to @question }
      else
        render 'new'
      end
    end
  end

  def edit
    @question = Question.find(params[:id])
  end

  def update
    @question = Question.find(params[:id])
    if @question.update_attributes(question_params)
      flash[:success] = "Question updated"
      redirect_to @question
    else
      render 'edit'
    end
  end

  def upvote
    @question = Question.find(params[:id])
    respond_to do |format|
      @question.upvote
      format.js {}
      format.html { redirect_to @question}
    end
  end

  def downvote
    @question = Question.find(params[:id])
    respond_to do |format|
      @question.downvote
      format.js {}
      format.html { redirect_to @question }
    end
  end

  def destroy
    Question.find(params[:id]).destroy
    flash[:success] = "Question deleted"
    redirect_to 'index'
  end

  private
    def question_params
      params.require(:question).permit(:title, :content)
    end
end

app/controllers/stack_overflow_controller.rb
class StackOverflowController < ApplicationController
  def index
  end

  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/stack_overflow_helper.rb
module StackOverflowHelper
end

app/views/answers/_answer.html.erb
<li id="answer-<%= answer.id %>">
  <div id="answer-votes-<%= answer.id %>">
    <%= render partial: 'answers/votes', locals: {answer: answer} %>
  </div>
  <br>
  Answer Title: <%= answer.title %>
  <br>
  Answer Content: <%= answer.content %>
  <br>
  Posted on: <%= answer.created_at %>
  (<%= link_to "Upvote", upvote_question_answer_path(question_id: answer.question.id, answer_id: answer.id), method: :patch, remote: true %>,
    <%= link_to "Downvote", downvote_question_answer_path(question_id: answer.question.id, answer_id: answer.id), method: :patch, remote: true %>)
</li>

app/views/answers/_votes.html.erb
Votes: <%= answer.votes %>

app/views/answers/create.js.erb
$("<%= escape_javascript(render @answer) %>").appendTo(".answers");

app/views/answers/downvote.js.erb
$('#answer-votes-<%= @answer.id %>').html("<%= escape_javascript render(:partial => 'answers/votes', :locals => { answer: @answer }) %>");

app/views/answers/upvote.js.erb
$('#answer-votes-<%= @answer.id %>').html("<%= escape_javascript render(:partial => 'answers/votes', :locals => { answer: @answer }) %>");

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %> | DBC Overflow</title>
  <link href='http://fonts.googleapis.com/css?family=PT+Sans:400,700,400italic' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="errors">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
  </div>
  <%= yield %>
  <%= debug(params) if Rails.env.development? %>
</body>
</html>

app/views/questions/_question.html.erb
  <li id="question-<%= question.id %>">
    <%= render partial: 'votes', locals: {question: question} %>
  </li>

app/views/questions/_votes.html.erb
Votes: <%= question.votes %> - <%= link_to question.title, question %>
(<%= link_to "Upvote", upvote_question_path(question.id), remote:true, method: :patch %>,
<%= link_to "Downvote", downvote_question_path(question.id), remote:true, method: :patch %>)

app/views/questions/create.js.erb
$("<%= escape_javascript(render @question) %>").appendTo(".questions");

app/views/questions/downvote.js.erb
$('#question-<%= @question.id %>').html("<%= escape_javascript render(:partial => 'votes', :locals => { question: @question }) %>");

app/views/questions/edit.html.erb
<% provide(:title, @question.title) %>
<h1>Edit Your Question</h1>

<div class="newQuestion">

  <%= form_for(@question) do |f| %>
    <%= render 'shared/error_messages' %>

    <%= f.label :title %>
    <%= f.text_field :title %>

    <%= f.label :content %>
    <%= f.text_field :content %>

    <%= f.submit "Submit my question" %>

  <% end %>

app/views/questions/index.html.erb
<% provide(:title, 'All Questions') %>

<div class="wrapper">
  <div class="quote">
    <h1>Quote of the day</h1>
    <i>"<%= @quote %>"</i>
  </div>

  <h1>All Posted Questions</h1>
  <h2>Total Questions: <%= @questions.count %></h2>


  <ol>
    <div class="questions">
      <% @questions.each do |question| %>
        <%= render partial: 'question', locals: {question: question} %>
        <% end %>
    </div>
  </ol>


  <h1>Create a new question</h1>

  <div class="newQuestion">

    <%= form_for(@question, remote: true) do |f| %>
      <%= render 'shared/error_messages' %>
      <%= f.label :title %>
      <%= f.text_field :title %>

      <%= f.label :content %>
      <%= f.text_area :content %>

      <%= f.submit "Submit my question" %>

    <% end %>
  </div>

  <h3>Question Preview</h3>
  <div class="liveDisplay">

    <h4>Title:</h4> <div id="questionTitle"></div>
    <h4>Content:</h4> <div id="questionContent"></div>

  </div>

</div>

app/views/questions/show.html.erb
<% provide(:title, @question.title) %>
<div class="questions">

  Question Title: <%= @question.title %>
  <br>
  Question Content: <%= @question.content %>
  <br>
  Edit Your Question: <%= link_to "Edit", edit_question_path(@question.id) %>
  <br>
  Delete Your Question: <%= link_to "Delete", @question, method: :delete, data: { confirm: "Are you sure you want to delete this question?"} %>
</div>
<br>
All available answers
<br>

  <h3>There are in total of <%= @question.answers.count %> to this question</h3>
  <ol>
    <div class="answers">
      <% @answers.each do |answer| %>
        <%= render partial: 'answers/answer', locals: {answer: answer} %>
      <% end %>
    </div>
  </ol>
  <%= will_paginate @answers %>
<% if @question.answers.count == 0 %>
  Sorry, there is currently no answers to this question. Post yours!
<% end %>


<div class="newAnswer">

  <%= form_for(@answer, url: question_answers_path(@question.id), remote: true) do |f| %>
    <%= render 'shared/error_messages' %>
    <%= f.label :title %>
    <%= f.text_field :title %>

    <%= f.label :content %>
    <%= f.text_field :content %>

    <%= f.submit "Submit my answer" %>

  <% end %>
</div>

app/views/questions/upvote.js.erb
$('#question-<%= @question.id %>').html("<%= escape_javascript render(:partial => 'votes', :locals => { question: @question }) %>");

app/views/shared/_error_messages.html.erb
<% if @question.errors.any? %>
  <h3>
    The form contains <%= pluralize(@quesiton.error.count, "error") %>
  </h3>
  <ul>
    <% @question.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

app/views/stack_overflow/index.html.erb
<% provide(:title, "Home") %>
<h1>StackOverflow#index</h1>
<p>Find me in app/views/stack_overflow/index.html.erb</p>

app/views/stack_overflow/show.html.erb
<% provide(:title, "Q/A") %>
<h1>StackOverflow#show</h1>
<p>Find me in app/views/stack_overflow/show.html.erb</p>